// GENERATED by scripts/build-public-facts.js from D1 (public_ok = 1, confirmed adult, first names only).
// Do not edit the names by hand; they are replaced on the next build. The how-to text is static.
// This file is the ONLY thing the public guide and the public search read. Neither queries D1.
export const PUBLIC_FACTS = {
  "siteName": "Team Lancaster",
  "founders": [
    "Example",
    "Sample"
  ],
  "branchParents": [
    "Test",
    "Demo"
  ],
  "howTo": [
    "This is a private, family-only site. Nothing here is indexed by search engines or archived.",
    "The front page shows the family crest and the first names of the founders and branch parents.",
    "Each branch has its own private area. To open yours, click \"Family members: open your branch\" and enter the passphrase your branch shared with you.",
    "If you do not have your branch passphrase, ask a family member in your branch. The guide cannot share passphrases.",
    "To fix or add something, use \"Request a change\" at the bottom of the page. Describe who it is about and what should change. A family admin reviews every request before anything changes.",
    "Inside a branch you will find that branch's tree, stories and photos, plus \"Ask the tree\" for questions about that branch."
  ]
};

export function factsAsText(f = PUBLIC_FACTS) {
  return [
    `Site: ${f.siteName}.`,
    `Founders (first names): ${f.founders.join(', ')}.`,
    `Branch parents (first names): ${f.branchParents.join(', ')}.`,
    ...f.howTo,
  ].join('\n');
}
